annotations:
  artifacthub.io/category: integration-delivery
  artifacthub.io/valuesSchema: "false"
  licenses: Apache-2.0
apiVersion: v2
description: The open source Firebase alternative. Patched version with db service fix.
home: https://supabase.com/
icon: https://avatars.githubusercontent.com/u/54469796?s=280&v=4
maintainers:
- email: sumvolika@bk.ru
  name: akkrevsky
name: supabase
type: application
version: 1.0.30